quickbooks:
  target: dev
  outputs:
    dev:
      type: redshift
      host: "{{ env_var('DBT_ENV_SECRET_DBT_HOST') }}"
      user: "{{ env_var('DBT_ENV_SECRET_DBT_USER') }}"
      pass: "{{ env_var('DBT_ENV_SECRET_DBT_PWD') }}"
      dbname: "{{ env_var('DBT_ENV_SECRET_DBT_DB') }}"
      port: 5439
      schema: fivetran_quickbooks
      threads: 8